# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

title: 개발블로그
email: cannalee90@gmail.com
description: 개발을 하고 사진을 찍습니다.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://cannalee90.github.io/" # the base hostname & protocol for your site

github_username:  cannalee90

# Build settings
markdown: kramdown
